### ISSUE TITLE
Revistit Elevator and Stair Distance Constants

### ISSUE THREAD

**Issue by SpiralGalaxy87** [CS321-Group1/OKTNav#2]
Once we have established a unit of distance, we need to give the elevators and stairs appropriate distance constants.
For reference, avg flight of stairs traversal is 13 seconds and avg elevator floor traversal is 36 seconds.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3255141/

**Comment by TSlaven19** [comment]
Closed for the reason that we are no longer doing multi-floor.
